### ISSUE TITLE
Gamelog Endpoint

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-visapi#1]
A web endpoint should be developed in Typescript, using Express to:
- [ ] throw an error if required environment variables not provided
- serve the most recent, non-served gamelog
  - [x] a gamelog can be retrieved from the database
  - [x] when a game log is served, it should be flagged as "served"
  - [x] return status code 200 with Gamelog
  - [x] return status code 204 Not Found if no games exist

Notes: 
- use Knex as a SQL client to connect to the database
- in the future this may be updated to only select the most recent not "served" game that played to completion
- any URLs/external information should be supplied via environment variables
- environment variables will probably include:
  - Database URL
  - Database Username
  - Database Password
  - Database Name

**Comment by russleyshaw** [comment]
do the thing

**Comment by russleyshaw** [comment]
asdf

**Comment by user404d** [comment]
What is the situation where we should throw an error if the env vars are not present? Currently they will just be assigned a default value. Do we want to change that behavior?
