### ISSUE TITLE
Merge colisee-visapi with colisee-api?

### ISSUE THREAD

**Issue by russleyshaw** [siggame/colisee-visapi#11]
The reason this wasn't done initially is we were hoping for more raw, and direct access from our components to GitLab and the database. 

Now we are wanting to abstract that away, specifically so that we don't have to require the front, competitor-facing web components to have intimate knowledge of our services and data. 

Now that we have this API, we can probably consider moving in the visapi to the actual api.

**Comment by user404d** [comment]
I think this is a good idea. We've already started making progress towards merging them together.

**Comment by russleyshaw** [comment]
(whoops i thought this was type/develop)
