### ISSUE TITLE
Add DB Backend

### ISSUE THREAD

**Issue by user404d** [siggame/colisee-visapi#4]
Effectively pull components from [colisee-matchmaker](https://github.com/siggame/colisee-matchmaker/blob/master/src/db.ts) in order to have a way to communicate with the database. 

What should be supported:

- Get n most recent games
- Update a selected game as 'visualized'

This will be subject to change as requirements become more solidified.

**Comment by MatthewQualls** [comment]
Now existing in `visapi.ts`:
- `getGamefile()` returning one `{id, gamelog}` pair
- `markVisualized(id)` which marks the game with id as visualized in the db
Commented out in `visapi.ts` are `getNNewGamelogs(num)` and `getNOldGamelogs(num)`, but these will likely be unnecessary in the scope of what we need visapi to d.
